module.exports = {
  STATES: {
    CONNECTING: 'CONNECTING',
    SUBSCRIBING: 'SUBSCRIBING',
    STABLE: 'STABLE',
    ISOLATED: 'ISOLATED',
    CONNECTING_INSUFFICIENT_PEERS: 'CONNECTING_INSUFFICIENT_PEERS',
  },
};
