module.exports = {
  HAPPN_SERVICE_STARTED: 'HAPPN_SERVICE_STARTED',
  HAPPN_SERVICE_STOPPED: 'HAPPN_SERVICE_STOPPED',
  HAPPN_SECURITY_DIRECTORY_CHANGED: 'HAPPN_SECURITY_DIRECTORY_CHANGED',
  HAPPN_SECURITY_DATA_CHANGED: 'security-data-changed',
  HAPPN_SESSION_AUTHENTICATE: 'authentic',
  HAPPN_SESSION_DISCONNECT: 'disconnect',
  SYSTEM_CLUSTER_SECURITY_DIRECTORY_REPLICATE: '_SYSTEM/CLUSTER_SECURITY_DIRECTORY_REPLICATE',
};
