name: CI Crypto-Utils

on: [push]

jobs:
  crypto-utils:
    env:
      RUNNING_IN_ACTIONS: yes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i -g npm@7 --registry=https://registry.npmjs.org
      - run: npm install

      - run: npm run lint --package_name=happn-util-crypto
      - run: npm run-script test-cover --workspace=happn-util-crypto

      - name: Generate coverage branch
        uses: team-tenacious/monorepo-coverage@main
        continue-on-error: true
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          COVERAGE_BRANCH: platform-coverage
          ROOT: './packages'
          PACKAGES: happn-util-crypto
