name: CI happner integration 3

on: [push]

jobs:
  happner:
    env:
        RUNNING_IN_ACTIONS: yes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ['4.4']
        redis-version: ['6']
        elastic-version: ['6.4.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - name: Start Elasticsearch
      uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: ${{ matrix.elastic-version }}
  
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: npm i -g npm@7 --registry=https://registry.npmjs.org
    - run: npm install

    - run: npm run-script test-cover-integration-3 --workspace=happner-2

    - name: Generate coverage branch
      uses: team-tenacious/monorepo-coverage@main
      continue-on-error: true
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        COVERAGE_BRANCH: platform-coverage
        ROOT: "./packages"
        PACKAGES: happner-2,happner-client

